<?php
#This file was last reorganized on 19th of September 2017 08:54:24 AM UTC

$text['title-server_errors']['en-us'] = "Server Errors";
$text['title-server_errors']['en-gb'] = "Server Errors";
$text['title-server_errors']['ar-eg'] = "أخطاء الخادم";
$text['title-server_errors']['de-at'] = "Serverfehler";
$text['title-server_errors']['de-ch'] = "Serverfehler";
$text['title-server_errors']['de-de'] = "Serverfehler";
$text['title-server_errors']['es-cl'] = "Errores del servidor";
$text['title-server_errors']['es-mx'] = "Errores del servidor";
$text['title-server_errors']['fr-ca'] = "Erreurs de serveur";
$text['title-server_errors']['fr-fr'] = "Erreurs de serveur";
$text['title-server_errors']['he-il'] = "שגיאות שרת";
$text['title-server_errors']['it-it'] = "Errori del server";
$text['title-server_errors']['nl-nl'] = "Server fouten";
$text['title-server_errors']['pl-pl'] = "Błędy serwera";
$text['title-server_errors']['pt-br'] = "Erros do servidor";
$text['title-server_errors']['pt-pt'] = "Erros do servidor";
$text['title-server_errors']['ro-ro'] = "Erori de server";
$text['title-server_errors']['ru-ru'] = "Ошибки сервера";
$text['title-server_errors']['sv-se'] = "Serverfel";
$text['title-server_errors']['uk-ua'] = "Помилки сервера";

$text['label-syntax']['en-us'] = "Syntax Highlighted";
$text['label-syntax']['en-gb'] = "Syntax Highlighted";
$text['label-syntax']['ar-eg'] = "تمييز بناء الجملة";
$text['label-syntax']['de-at'] = "Syntax Highlighted"; //copied from de-de
$text['label-syntax']['de-ch'] = "Syntax Highlighted"; //copied from de-de
$text['label-syntax']['de-de'] = "Syntax Highlighted";
$text['label-syntax']['es-cl'] = "Destacar Sintaxis";
$text['label-syntax']['es-mx'] = "Destacar Sintaxis"; //copied from es-cl
$text['label-syntax']['fr-ca'] = "Coloration Syntaxique"; //copied from fr-fr
$text['label-syntax']['fr-fr'] = "Coloration Syntaxique";
$text['label-syntax']['he-il'] = "תחביר מודגש";
$text['label-syntax']['it-it'] = "Sintassi Evidenziata";
$text['label-syntax']['nl-nl'] = "Syntax uitlichten";
$text['label-syntax']['pl-pl'] = "Składnia wyróżniona";
$text['label-syntax']['pt-br'] = "Realçar a sintaxe";
$text['label-syntax']['pt-pt'] = "Realçar a Sintaxe";
$text['label-syntax']['ro-ro'] = "Sintaxă evidențiată";
$text['label-syntax']['ru-ru'] = "Выделение Синтаксиса";
$text['label-syntax']['sv-se'] = "Syntax Markerad";
$text['label-syntax']['uk-ua'] = "Підсвічування синтаксису";

$text['label-sort']['en-us'] = "Sort Descending";
$text['label-sort']['en-gb'] = "Sort Descending";
$text['label-sort']['ar-eg'] = "ترتيب تنازلي";
$text['label-sort']['de-at'] = "Absteigend sortiert"; //copied from de-de
$text['label-sort']['de-ch'] = "Absteigend sortiert"; //copied from de-de
$text['label-sort']['de-de'] = "Absteigend sortiert";
$text['label-sort']['es-cl'] = "Mostrar en orden descendente";
$text['label-sort']['es-mx'] = "Mostrar en orden descendente"; //copied from es-cl
$text['label-sort']['fr-ca'] = "Affichage ordre descendant"; //copied from fr-fr
$text['label-sort']['fr-fr'] = "Affichage ordre descendant";
$text['label-sort']['he-il'] = "מיין יורד";
$text['label-sort']['it-it'] = "Ordina a Scendere";
$text['label-sort']['nl-nl'] = "Sorteer aflopend";
$text['label-sort']['pl-pl'] = "Sortuj malejąco";
$text['label-sort']['pt-br'] = "Ordenar por tipo";
$text['label-sort']['pt-pt'] = "Ordenar Descendetemente";
$text['label-sort']['ro-ro'] = "Sortează descrescător";
$text['label-sort']['ru-ru'] = "Сортировка по убыванию";
$text['label-sort']['sv-se'] = "Sortera Fallande";
$text['label-sort']['uk-ua'] = "Сортувати за спаданням";

$text['label-open_file']['en-us'] = "Opening entire file...";
$text['label-open_file']['en-gb'] = "Opening entire file...";
$text['label-open_file']['ar-eg'] = "يتم فتح الملف بأكمله ...";
$text['label-open_file']['de-at'] = "gesamte Datei öffnen"; //copied from de-de
$text['label-open_file']['de-ch'] = "gesamte Datei öffnen"; //copied from de-de
$text['label-open_file']['de-de'] = "gesamte Datei öffnen";
$text['label-open_file']['es-cl'] = "Abrir el archivo completo";
$text['label-open_file']['es-mx'] = "Abrir el archivo completo"; //copied from es-cl
$text['label-open_file']['fr-ca'] = "Ouvrir le fichier entier"; //copied from fr-fr
$text['label-open_file']['fr-fr'] = "Ouvrir le fichier entier";
$text['label-open_file']['he-il'] = "פותח את כל הקובץ...";
$text['label-open_file']['it-it'] = "Apertura completa file";
$text['label-open_file']['nl-nl'] = "Open het gehele bestand...";
$text['label-open_file']['pl-pl'] = "otwarcie całego pliku";
$text['label-open_file']['pt-br'] = "Abrir um arquivo todo";
$text['label-open_file']['pt-pt'] = "abrir o ficheiro todo";
$text['label-open_file']['ro-ro'] = "Se deschide întregul fișier...";
$text['label-open_file']['ru-ru'] = "Открытие всего файла";
$text['label-open_file']['sv-se'] = "Öppnar hela filen";
$text['label-open_file']['uk-ua'] = "відкрито весь файл";

$text['label-open_at']['en-us'] = "opening at";
$text['label-open_at']['en-gb'] = "opening at";
$text['label-open_at']['ar-eg'] = "يفتح في";
$text['label-open_at']['de-at'] = "öffnen"; //copied from de-de
$text['label-open_at']['de-ch'] = "öffnen"; //copied from de-de
$text['label-open_at']['de-de'] = "öffnen";
$text['label-open_at']['es-cl'] = "Abrir en";
$text['label-open_at']['es-mx'] = "Abrir en"; //copied from es-cl
$text['label-open_at']['fr-ca'] = "Ouvrir à"; //copied from fr-fr
$text['label-open_at']['fr-fr'] = "Ouvrir à";
$text['label-open_at']['he-il'] = "פתיחה ב";
$text['label-open_at']['it-it'] = "Aperto a";
$text['label-open_at']['nl-nl'] = "openen vanaf";
$text['label-open_at']['pl-pl'] = "otwarcie na";
$text['label-open_at']['pt-br'] = "Abrir";
$text['label-open_at']['pt-pt'] = "abrir";
$text['label-open_at']['ro-ro'] = "deschidere la";
$text['label-open_at']['ru-ru'] = "Открытие на";
$text['label-open_at']['sv-se'] = "Öppnar vid";
$text['label-open_at']['uk-ua'] = "відкрито о";

$text['header-server_errors']['en-us'] = "Server Errors";
$text['header-server_errors']['en-gb'] = "Server Errors";
$text['header-server_errors']['ar-eg'] = "أخطاء الخادم";
$text['header-server_errors']['de-at'] = "Serverfehler";
$text['header-server_errors']['de-ch'] = "Serverfehler";
$text['header-server_errors']['de-de'] = "Serverfehler";
$text['header-server_errors']['es-cl'] = "Errores del servidor";
$text['header-server_errors']['es-mx'] = "Errores del servidor";
$text['header-server_errors']['fr-ca'] = "Erreurs de serveur";
$text['header-server_errors']['fr-fr'] = "Erreurs de serveur";
$text['header-server_errors']['he-il'] = "שגיאות שרת";
$text['header-server_errors']['it-it'] = "Errori del server";
$text['header-server_errors']['nl-nl'] = "Server fouten";
$text['header-server_errors']['pl-pl'] = "Błędy serwera";
$text['header-server_errors']['pt-br'] = "Erros do servidor";
$text['header-server_errors']['pt-pt'] = "Erros do servidor";
$text['header-server_errors']['ro-ro'] = "Erori de server";
$text['header-server_errors']['ru-ru'] = "Ошибки сервера";
$text['header-server_errors']['sv-se'] = "Serverfel";
$text['header-server_errors']['uk-ua'] = "Помилки сервера";

$text['label-line_numbers']['en-us'] = "Line Numbers";
$text['label-line_numbers']['en-gb'] = "Line Numbers";
$text['label-line_numbers']['ar-eg'] = "أرقام الأسطر";
$text['label-line_numbers']['de-at'] = "Zeilennummern anzeigen"; //copied from de-de
$text['label-line_numbers']['de-ch'] = "Zeilennummern anzeigen"; //copied from de-de
$text['label-line_numbers']['de-de'] = "Zeilennummern anzeigen";
$text['label-line_numbers']['es-cl'] = "Mostrar números de línea";
$text['label-line_numbers']['es-mx'] = "Mostrar números de línea"; //copied from es-cl
$text['label-line_numbers']['fr-ca'] = "Afficher les numéros de ligne"; //copied from fr-fr
$text['label-line_numbers']['fr-fr'] = "Afficher les numéros de ligne";
$text['label-line_numbers']['he-il'] = "מספרי שורות";
$text['label-line_numbers']['it-it'] = "Mostra Numeri di Riga";
$text['label-line_numbers']['nl-nl'] = "Regelnummers";
$text['label-line_numbers']['pl-pl'] = "Pokaż numery wierszy";
$text['label-line_numbers']['pt-br'] = "Mostrar números das linhas";
$text['label-line_numbers']['pt-pt'] = "Mostrar Números das Linhas";
$text['label-line_numbers']['ro-ro'] = "Numere de linie";
$text['label-line_numbers']['ru-ru'] = "Показывать номера строк";
$text['label-line_numbers']['sv-se'] = "Visa Linje Nummer";
$text['label-line_numbers']['uk-ua'] = "Нумерація рядків";

$text['label-lines']['en-us'] = "Lines";
$text['label-lines']['en-gb'] = "Lines";
$text['label-lines']['ar-eg'] = "خطوط";
$text['label-lines']['de-at'] = "Linien";
$text['label-lines']['de-ch'] = "Linien";
$text['label-lines']['de-de'] = "Linien";
$text['label-lines']['es-cl'] = "Líneas";
$text['label-lines']['es-mx'] = "Líneas";
$text['label-lines']['fr-ca'] = "Lignes";
$text['label-lines']['fr-fr'] = "Lignes";
$text['label-lines']['he-il'] = "שורות";
$text['label-lines']['it-it'] = "Linee";
$text['label-lines']['nl-nl'] = "Regels";
$text['label-lines']['pl-pl'] = "Linie";
$text['label-lines']['pt-br'] = "Linhas";
$text['label-lines']['pt-pt'] = "Linhas";
$text['label-lines']['ro-ro'] = "Linii";
$text['label-lines']['ru-ru'] = "Линии";
$text['label-lines']['sv-se'] = "Rader";
$text['label-lines']['uk-ua'] = "Лінії";

$text['label-log']['en-us'] = "Log";
$text['label-log']['en-gb'] = "Log";
$text['label-log']['ar-eg'] = "سجل";
$text['label-log']['de-at'] = "Protokoll";
$text['label-log']['de-ch'] = "Protokoll";
$text['label-log']['de-de'] = "Protokoll";
$text['label-log']['es-cl'] = "Registro";
$text['label-log']['es-mx'] = "Registro";
$text['label-log']['fr-ca'] = "Journal";
$text['label-log']['fr-fr'] = "Journal";
$text['label-log']['he-il'] = "עֵץ";
$text['label-log']['it-it'] = "Tronco d'albero";
$text['label-log']['nl-nl'] = "Log";
$text['label-log']['pl-pl'] = "Dziennik";
$text['label-log']['pt-br'] = "Registro";
$text['label-log']['pt-pt'] = "Registro";
$text['label-log']['ro-ro'] = "Buturuga";
$text['label-log']['ru-ru'] = "Бревно";
$text['label-log']['sv-se'] = "Logga";
$text['label-log']['uk-ua'] = "Журнал";

$text['label-current']['en-us'] = "Current";
$text['label-current']['en-gb'] = "Current";
$text['label-current']['ar-eg'] = "حاضِر";
$text['label-current']['de-at'] = "Aktuell";
$text['label-current']['de-ch'] = "Aktuell";
$text['label-current']['de-de'] = "Aktuell";
$text['label-current']['es-cl'] = "Actual";
$text['label-current']['es-mx'] = "Actual";
$text['label-current']['fr-ca'] = "Actuel";
$text['label-current']['fr-fr'] = "Actuel";
$text['label-current']['he-il'] = "נוֹכְחִי";
$text['label-current']['it-it'] = "Attuale";
$text['label-current']['nl-nl'] = "Aktueel";
$text['label-current']['pl-pl'] = "Aktualny";
$text['label-current']['pt-br'] = "Atual";
$text['label-current']['pt-pt'] = "Atual";
$text['label-current']['ro-ro'] = "Actual";
$text['label-current']['ru-ru'] = "Текущий";
$text['label-current']['sv-se'] = "Nuvarande";
$text['label-current']['uk-ua'] = "поточний";

$text['label-previous']['en-us'] = "Previous";
$text['label-previous']['en-gb'] = "Previous";
$text['label-previous']['ar-eg'] = "سابق";
$text['label-previous']['de-at'] = "Vorherige";
$text['label-previous']['de-ch'] = "Vorherige";
$text['label-previous']['de-de'] = "Vorherige";
$text['label-previous']['es-cl'] = "Previo";
$text['label-previous']['es-mx'] = "Previo";
$text['label-previous']['fr-ca'] = "Précédent";
$text['label-previous']['fr-fr'] = "Précédent";
$text['label-previous']['he-il'] = "קודם";
$text['label-previous']['it-it'] = "Precedente";
$text['label-previous']['nl-nl'] = "Vorig";
$text['label-previous']['pl-pl'] = "Poprzedni";
$text['label-previous']['pt-br'] = "Anterior";
$text['label-previous']['pt-pt'] = "Anterior";
$text['label-previous']['ro-ro'] = "Anterior";
$text['label-previous']['ru-ru'] = "Предыдущий";
$text['label-previous']['sv-se'] = "Tidigare";
$text['label-previous']['uk-ua'] = "Попередній";

$text['label-filter']['en-us'] = "Filter";
$text['label-filter']['en-gb'] = "Filter";
$text['label-filter']['ar-eg'] = "منقي";
$text['label-filter']['de-at'] = "Filter"; //copied from de-de
$text['label-filter']['de-ch'] = "Filter"; //copied from de-de
$text['label-filter']['de-de'] = "Filter";
$text['label-filter']['es-cl'] = "Filtrar";
$text['label-filter']['es-mx'] = "Filtrar"; //copied from es-cl
$text['label-filter']['fr-ca'] = "Filtre"; //copied from fr-fr
$text['label-filter']['fr-fr'] = "Filtre";
$text['label-filter']['he-il'] = "לְסַנֵן";
$text['label-filter']['it-it'] = "Filtro";
$text['label-filter']['nl-nl'] = "Filter";
$text['label-filter']['pl-pl'] = "Filtr";
$text['label-filter']['pt-br'] = "Filtro"; //copied from pt-pt
$text['label-filter']['pt-pt'] = "Filtro";
$text['label-filter']['ro-ro'] = "Filtru";
$text['label-filter']['ru-ru'] = "Фильтр";
$text['label-filter']['sv-se'] = "Filter";
$text['label-filter']['uk-ua'] = "Фільтр";

$text['label-display']['en-us'] = "Display";
$text['label-display']['en-gb'] = "Display";
$text['label-display']['ar-eg'] = "عرض";
$text['label-display']['de-at'] = "letztes anzeigen"; //copied from de-de
$text['label-display']['de-ch'] = "letztes anzeigen"; //copied from de-de
$text['label-display']['de-de'] = "letztes anzeigen";
$text['label-display']['es-cl'] = "Mostrando últimos eventos";
$text['label-display']['es-mx'] = "Mostrando últimos eventos"; //copied from es-cl
$text['label-display']['fr-ca'] = "Afficher les derniers"; //copied from fr-fr
$text['label-display']['fr-fr'] = "Afficher les derniers";
$text['label-display']['he-il'] = "לְהַצִיג";
$text['label-display']['it-it'] = "Mostra l'ultimo";
$text['label-display']['nl-nl'] = "Toon";
$text['label-display']['pl-pl'] = "Wyświetlanie od ostatniego";
$text['label-display']['pt-br'] = "Mostrar o último"; //copied from pt-pt
$text['label-display']['pt-pt'] = "Mostrar o último";
$text['label-display']['ro-ro'] = "Afişa";
$text['label-display']['ru-ru'] = "Отображение последнего";
$text['label-display']['sv-se'] = "Visar den sista";
$text['label-display']['uk-ua'] = "Показувати останні";

$text['error-open_file']['en-us'] = "Unable to open file!";
$text['error-open_file']['en-gb'] = "Unable to open file!";
$text['error-open_file']['ar-eg'] = "غير قادر على فتح ملف!";
$text['error-open_file']['de-at'] = "Datei kann nicht geöffnet werden!"; //copied from de-de
$text['error-open_file']['de-ch'] = "Datei kann nicht geöffnet werden!"; //copied from de-de
$text['error-open_file']['de-de'] = "Datei kann nicht geöffnet werden!";
$text['error-open_file']['es-cl'] = "¡Imposible abrir el archivo!";
$text['error-open_file']['es-mx'] = "¡Imposible abrir el archivo!"; //copied from es-cl
$text['error-open_file']['fr-ca'] = "Impossible d'ouvrir le fichier!"; //copied from fr-fr
$text['error-open_file']['fr-fr'] = "Impossible d'ouvrir le fichier!";
$text['error-open_file']['he-il'] = "לא מצליח לפתוח את הקובץ!";
$text['error-open_file']['it-it'] = "Impossibile aprire il file!";
$text['error-open_file']['nl-nl'] = "Kan bestand niet openen!";
$text['error-open_file']['pl-pl'] = "Nie można otworzyć pliku!";
$text['error-open_file']['pt-br'] = "Impossivel abrir o arquivo";
$text['error-open_file']['pt-pt'] = "Impossível abrir o ficheiro!";
$text['error-open_file']['ro-ro'] = "Fisierul nu poate fi deschis!";
$text['error-open_file']['ru-ru'] = "Невозможно открыть файл!";
$text['error-open_file']['sv-se'] = "Kan inte öppna fil!";
$text['error-open_file']['uk-ua'] = "Неможливо відкрити файл!";

?>
